---
title: "Homework 1"
subtitle: "Introduction to Network Analysis"
author: "Aleksey Shadrunov (Group 2, asshadrunov@edu.hse.ru)"
date: "`r Sys.Date()`"
indent: true
output: 
  pdf_document:
    toc: true
    toc_depth: 3
    extra_dependencies: ["float"]
header-includes:
    - \usepackage{indentfirst}
---

\newpage

# prepare packages and load data  
install packages (uncomment if needed):  
```{r}
# on arch you might need to install gcc-fortran (necessary for compiling igraph)
# on arch you might need to install glpk (necessary for compiling igraph)

# install.packages("network", repos = "https://mirror.truenetwork.ru/CRAN/")
# install.packages("sna")
# install.packages("igraph")
# remove.packages("igraph")
# # if there are some problems with the package above:
# remotes::install_github("igraph/rigraph@master")
# install.packages("intergraph")
# install.packages("knitr")
# install.packages("CINNA")
# install.packages("RColorBrewer", repos = "https://mirror.truenetwork.ru/CRAN/")
# install.packages("bipartite", repos = "https://mirror.truenetwork.ru/CRAN/")
```  
  
load data `trade.Rdata`:  

```{r}
library(bipartite)
library(network)
library(RColorBrewer)
```
```{r}
# dutchelite <- read.paj("hw3/DutchElite.paj")
# dutchelite <- read.paj("hw3/Top200.paj")
dutchelite <- read.paj("hw3/Top201.paj")
```

```{r}
names(dutchelite)
names(dutchelite$networks)
names(dutchelite$partitions)

pastel2 <- brewer.pal(8, "Pastel2")
accent <- brewer.pal(5, "Accent")

de_matrix <- as.matrix.network(dutchelite$networks[[1]]$networks[[4]], na.rm = TRUE, expand.bipartite = FALSE)
de_onemode_matrix <- as.one.mode(de_matrix, project = "lower")
```


```{r}
de_onemode_matrix
de_onemode_network <- as.network.matrix(de_onemode_matrix, directed = FALSE)
de_onemode_network

delete.vertices(de_onemode_network, which(degree(de_onemode_network) < 1))
de_components <- component.dist(de_onemode_network)
de_components$membership
delete.vertices(de_onemode_network, which(de_components$membership > 1))

plot(
    de_onemode_network,
    mode = "fruchtermanreingold",
    displaylabels = TRUE,
    label.cex = 1.6,
    vertex.col = accent[1],
    edge.col = pastel2[8],
    label.col = accent[5]
)

plot(de_onemode_network)
```

